/* Populated by react-webpack-redux:action */
export const SHOW_ALERT = 'SHOW_ALERT';

export const FETCH_CONFIG = 'FETCH_CONFIG';
export const REQUEST_CONFIG = 'REQUEST_CONFIG';
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';
export const ERROR_CONFIG = 'ERROR_CONFIG';

export const FETCH_TRANSLATIONS = 'FETCH_TRANSLATIONS';
export const REQUEST_TRANSLATIONS = 'REQUEST_TRANSLATIONS';
export const RECEIVE_TRANSLATIONS = 'RECEIVE_TRANSLATIONS';
export const ERROR_TRANSLATIONS = 'ERROR_TRANSLATIONS';

export const FETCH_PROVIDER= 'FETCH_PROVIDER_DATA';
export const REQUEST_PROVIDER = 'REQUEST_PROVIDER_DATA';
export const RECEIVE_PROVIDER = 'RECEIVE_PROVIDER_DATA';
export const ERROR_PROVIDER = 'ERROR_PROVIDER_DATA';